app_admin:
    resource: "@AppAdminBundle/Resources/config/routing.yml"
    prefix:   /

app_content:
    resource: "@AppContentBundle/Resources/config/routing.yml"
    prefix:   /

app_core:
    resource: "@AppCoreBundle/Resources/config/routing.yml"
    prefix:   /


