app.admin:
    path:     /
    defaults: { _controller: AppAdminBundle:Admin:main }

app.admin.page.list:
    path:    /pages
    defaults: { _controller: AppAdminBundle:Page:list }
    
app.admin.page.show:
    path:    /page/show/{page}
    defaults: { _controller: AppAdminBundle:Page:show }

app.admin.page.add:
    path:    /page/add
    defaults: { _controller: AppAdminBundle:Page:add }
    
app.admin.page.edit:
    path:    /page/edit/{page}
    defaults: { _controller: AppAdminBundle:Page:edit }
    
app.admin.page:
    path:    /page/{page}
    defaults: { _controller: AppAdminBundle:Page:page }
