app.admin:
    path:     /admin
    defaults: { _controller: AppAdminBundle:Admin:main }

app.admin.page.list:
    path:    /admin/pages
    defaults: { _controller: AppAdminBundle:Page:list }
    
app.admin.page.show:
    path:    /admin/page/show/{page}
    defaults: { _controller: AppAdminBundle:Page:show }

app.admin.page.add:
    path:    /admin/page/add
    defaults: { _controller: AppAdminBundle:Page:add }
    
app.admin.page.edit:
    path:    /admin/page/edit/{page}
    defaults: { _controller: AppAdminBundle:Page:edit }
    
app.admin.page:
    path:    /admin/page/{page}
    defaults: { _controller: AppAdminBundle:Page:page }
