core_page:
    path:     /page/{pageId}
    defaults: { _controller: AppCoreBundle:Page:page }
    
core_element:
    path:     /element/{element}
    defaults: { _controller: AppCoreBundle:Page:element }

core_element_create:
    path:     /element/create/{page}/{elementName}
    defaults: { _controller: AppCoreBundle:Element:create }
    
core_element_list:
    path:     /element/list/{page}
    defaults: { _controller: AppCoreBundle:Element:list }
    
core_placement_sort:
    path:     /placement/sort/{page}
    defaults: { _controller: AppCoreBundle:Element:sort }
    
core_placement_remove:
    path:     /placement/remove/{placement}
    defaults: { _controller: AppCoreBundle:Element:remove }